# Generated by Django 4.0.4 on 2022-05-30 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('address1', models.CharField(max_length=60, verbose_name='Address Line 1')),
                ('address2', models.CharField(max_length=60, verbose_name='Address Line 2')),
                ('zip_code', models.CharField(max_length=12, verbose_name='Zip/Postal Code')),
                ('city', models.CharField(max_length=40)),
                ('country', models.CharField(choices=[('UK', 'United Kingdom'), ('USA', 'United State of America'), ('BD', 'Bangladesh')], max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
