# Generated by Django 4.0.4 on 2022-06-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_order_orderline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address2',
            field=models.CharField(blank=True, max_length=120, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_address2',
            field=models.CharField(blank=True, max_length=120, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address2',
            field=models.CharField(blank=True, max_length=120, verbose_name='Address Line 2'),
        ),
    ]
