# Generated by Django 4.0.4 on 2022-06-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_address_address2_alter_order_billing_address2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(default='Unknown', max_length=60),
        ),
    ]
