# Generated by Django 4.0.4 on 2022-06-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_product_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_slide', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='home-sliders')),
                ('alt_text', models.CharField(max_length=20)),
                ('caption_header', models.CharField(max_length=30)),
                ('caption_text', models.CharField(max_length=60)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
